### ISSUE TITLE
请问可以提供数据集和train代码吗？

### ISSUE THREAD

**Issue by ShenFey** [LiuFei-AHU/MPSFFA#1]
你好，研读了您的这篇论文，很有启发，想要试一试，请问可以提供全部代码吗？

**Comment by LiuFei-AHU** [comment]
It is my pleasure that my paper can give you a little inspiration. Hope you can follow it and do better works.
At present, I am busy at a project, and I will post the full code latter. Please email me (liu.jason0728@gmail.com) if you need the data.

**Comment by LiuFei-AHU** [comment]
The demo implementation of the MPS-FFA is provided. Please refer to the codes. Hope it can solve your problems.

**Comment by ShenFey** [comment]
Hi,Liu Fei,
I saw it.Thank you for taking time out of your busy schedule to upload the code.
I have downloaded the code you uploaded,&nbsp;
but it marked an error at “from train import train_mmse_similarity as train”.

It looks like&nbsp; missing the&nbsp; file named "train".
Is there any document missing&nbsp;by accident?&nbsp;Or do I need to do something else?



&nbsp;Best wishes,

Shen Fei








ShenFey
***@***.***



&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LiuFei-AHU/MPSFFA"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月1日(星期五) 下午2:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [LiuFei-AHU/MPSFFA] 请问可以提供数据集和train代码吗？ (Issue #1)





 
The demo implementation of the MPS-FFA is provided. Please refer to the codes. Hope it can solve your problems.

**Comment by LiuFei-AHU** [comment]
I forgot to upload this file. :grin: I have uploaded it to Github.

**Comment by ShenFey** [comment]
Good morning，Liu Fei,
I'm sorry about a&nbsp;pity&nbsp;happened.It looks like we&nbsp;missing another file&nbsp; marked&nbsp;at
“from torchmetrics.classification import BinaryAccuracy” when I tried again.



Best Wishes,
Shen Fei












ShenFey
***@***.***



&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LiuFei-AHU/MPSFFA"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月1日(星期五) 晚上10:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [LiuFei-AHU/MPSFFA] 请问可以提供数据集和train代码吗？ (Issue #1)





 
I forgot to upload this file. 😁 I have uploaded it to Github.

**Comment by LiuFei-AHU** [comment]
You should install the 'torchmetrics' into your conda enviroment.

**Comment by xingyunjohn1** [comment]
I have read your paper and found it inspiring. I am now interested in replicating the study. Could you please provide some sample data or inform me about the shape of the three-dimensional MRI images that should be input into the network?
