### ISSUE TITLE
关于训练配置

### ISSUE THREAD

**Issue by charmm09** [LiuFei-AHU/MPSFFA#2]
你好作者！我尝试用自己的数据复现你的实验，但是报错torch.OutOfMemoryError: CUDA out of memory. 请问是因为硬件配置的问题吗？方便说一下你的硬件配置吗？

**Comment by LiuFei-AHU** [comment]
你好。这个问题的原因很可能是机器显存不足。你可以将batch_size调小一点试试，例如，你可以先尝试将batch_size设置为2。如果这样能够正常运行，你再尝试逐渐调大你的batch_size。此外，你还可以将image_size裁剪的小一些。当然，也可以使用torch.cuda.empty_cache()清理一下cuda的缓存试试。  如果上述操作都不能解决问题，建议你换一个有更大显存的显卡试试。

**Comment by charmm09** [comment]
好的谢谢！
